"""initial schema

Revision ID: c202af4059bb
Revises: 
Create Date: 2026-09-20 06:04:30.063947
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c202af4059bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trade', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RESTRICTED', 'DEBARRED', name='contractorstatus', native_enum=False, length=48), nullable=False),
    sa.Column('registered_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractors')),
    sa.UniqueConstraint('code', name='uq_contractors_code')
    )
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contractors_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_contractors_status'), ['status'], unique=False)

    op.create_table('model_artifacts',
    sa.Column('model_kind', sa.Enum('ACCIDENT_RISK_SUPERVISED', 'SENSOR_ANOMALY_ISOLATION_FOREST', 'RULE_BASED_BASELINE', name='modelkind', native_enum=False, length=48), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UNTRAINED', 'TRAINED', 'ARTIFACT_MISSING', name='modelstatus', native_enum=False, length=48), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('feature_schema', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_artifacts')),
    sa.UniqueConstraint('model_kind', 'version', name='uq_model_artifacts')
    )
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_artifacts_model_kind'), ['model_kind'], unique=False)

    op.create_table('statutory_rules',
    sa.Column('rule_code', sa.String(length=48), nullable=False),
    sa.Column('statute', sa.String(length=160), nullable=False),
    sa.Column('clause', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('obligation_type', sa.Enum('RECURRING_MEETING', 'RECURRING_INSPECTION', 'RECURRING_MEASUREMENT', 'CERTIFICATE_VALIDITY', 'CONTINUOUS_STANDARD', 'EVENT_NOTIFICATION', name='obligationtype', native_enum=False, length=48), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=True),
    sa.Column('applies_to_underground', sa.Boolean(), nullable=False),
    sa.Column('applies_to_opencast', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=48), nullable=False),
    sa.Column('evidence_required', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=120), nullable=False),
    sa.Column('clause_verification', sa.Enum('UNVERIFIED', 'VERIFIED', 'DISPUTED', name='clauseverification', native_enum=False, length=48), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statutory_rules')),
    sa.UniqueConstraint('rule_code', name='uq_statutory_rules_rule_code')
    )
    with op.batch_alter_table('statutory_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_rules_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_rules_severity'), ['severity'], unique=False)

    op.create_table('subsidiaries',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subsidiaries')),
    sa.UniqueConstraint('code', name='uq_subsidiaries_code')
    )
    with op.batch_alter_table('subsidiaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subsidiaries_code'), ['code'], unique=False)

    op.create_table('mines',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mine_type', sa.Enum('UNDERGROUND', 'OPENCAST', 'MIXED', name='minetype', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='minestatus', native_enum=False, length=48), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coordinate_is_approximate', sa.Boolean(), nullable=False),
    sa.Column('coordinate_provenance', sa.Enum('REAL_PUBLIC_DATA', 'SIMULATED', 'DEMO', 'LIVE_EXTERNAL_API', 'DEMO_FALLBACK', 'USER_SUPPLIED', name='dataprovenance', native_enum=False, length=48), nullable=False),
    sa.Column('coordinate_note', sa.Text(), nullable=True),
    sa.Column('production_hours_last_year', sa.Float(), nullable=True),
    sa.Column('average_employee_count', sa.Integer(), nullable=True),
    sa.Column('subsidiary_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name=op.f('fk_mines_subsidiary_id_subsidiaries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mines')),
    sa.UniqueConstraint('code', name='uq_mines_code')
    )
    with op.batch_alter_table('mines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mines_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mines_mine_type'), ['mine_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mines_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mines_subsidiary_id'), ['subsidiary_id'], unique=False)

    op.create_table('contractor_sites',
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_contractor_sites_contractor_id_contractors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_contractor_sites_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractor_sites')),
    sa.UniqueConstraint('contractor_id', 'mine_id', name='uq_contractor_sites_pair')
    )
    with op.batch_alter_table('contractor_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contractor_sites_contract_end'), ['contract_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_contractor_sites_contractor_id'), ['contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contractor_sites_mine_id'), ['mine_id'], unique=False)

    op.create_table('environmental_readings',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_kind', sa.Enum('METHANE', 'CARBON_MONOXIDE', 'AIRFLOW', name='sensorkind', native_enum=False, length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_label', sa.String(length=120), nullable=True),
    sa.Column('provenance', sa.Enum('REAL_PUBLIC_DATA', 'SIMULATED', 'DEMO', 'LIVE_EXTERNAL_API', 'DEMO_FALLBACK', 'USER_SUPPLIED', name='dataprovenance', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_environmental_readings_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environmental_readings'))
    )
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.create_index('ix_env_readings_mine_time', ['mine_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_environmental_readings_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environmental_readings_provenance'), ['provenance'], unique=False)
        batch_op.create_index(batch_op.f('ix_environmental_readings_sensor_kind'), ['sensor_kind'], unique=False)

    op.create_table('ml_features',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('window_end_date', sa.Date(), nullable=False),
    sa.Column('violations_last_12m', sa.Integer(), nullable=True),
    sa.Column('ss_violations_last_12m', sa.Integer(), nullable=True),
    sa.Column('repeat_violation_ratio', sa.Float(), nullable=True),
    sa.Column('days_since_last_inspection', sa.Integer(), nullable=True),
    sa.Column('inspection_hours_last_12m', sa.Float(), nullable=True),
    sa.Column('avg_penalty_amount', sa.Float(), nullable=True),
    sa.Column('mine_size_avg_employees', sa.Float(), nullable=True),
    sa.Column('production_hours', sa.Float(), nullable=True),
    sa.Column('mine_type', sa.String(length=32), nullable=True),
    sa.Column('expired_documents', sa.Integer(), nullable=True),
    sa.Column('overdue_obligations', sa.Integer(), nullable=True),
    sa.Column('overdue_capa_items', sa.Integer(), nullable=True),
    sa.Column('open_incidents', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.Enum('REAL_PUBLIC_DATA', 'SIMULATED', 'DEMO', 'LIVE_EXTERNAL_API', 'DEMO_FALLBACK', 'USER_SUPPLIED', name='dataprovenance', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_ml_features_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_features')),
    sa.UniqueConstraint('mine_id', 'window_end_date', name='uq_ml_features_mine_window')
    )
    with op.batch_alter_table('ml_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_features_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index('ix_ml_features_window', ['window_end_date'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DGMS_REGULATOR', 'SUBSIDIARY_HEAD', 'MINE_MANAGER', 'MINE_SAFETY_OFFICER', 'FIELD_INSPECTOR', name='role', native_enum=False, length=48), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mine_id', sa.Uuid(), nullable=True),
    sa.Column('subsidiary_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_users_mine_id_mines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subsidiary_id'], ['subsidiaries.id'], name=op.f('fk_users_subsidiary_id_subsidiaries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_subsidiary_id'), ['subsidiary_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('seq', name='uq_audit_log_seq')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_log_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_row_hash'), ['row_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('devices',
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('fingerprint', name='uq_devices_fingerprint')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('contractor_id', sa.Uuid(), nullable=True),
    sa.Column('doc_type', sa.String(length=120), nullable=False),
    sa.Column('certificate_no', sa.String(length=160), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('ocr_engine', sa.Enum('TESSERACT', 'BHASHINI', 'DEMO_FALLBACK', 'NONE', name='ocrengine', native_enum=False, length=48), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', name='verificationstatus', native_enum=False, length=48), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_documents_contractor_id_contractors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_documents_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['statutory_rules.id'], name=op.f('fk_documents_rule_id_statutory_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_documents_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_contractor_id'), ['contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_verification_status'), ['verification_status'], unique=False)

    op.create_table('ml_predictions',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('model_kind', sa.Enum('ACCIDENT_RISK_SUPERVISED', 'SENSOR_ANOMALY_ISOLATION_FOREST', 'RULE_BASED_BASELINE', name='modelkind', native_enum=False, length=48), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('explanation_method', sa.String(length=48), nullable=True),
    sa.Column('overridden_by', sa.Uuid(), nullable=True),
    sa.Column('override_score', sa.Float(), nullable=True),
    sa.Column('override_justification', sa.Text(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_ml_predictions_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], name=op.f('fk_ml_predictions_overridden_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_predictions'))
    )
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_predictions_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index('ix_ml_predictions_mine_kind', ['mine_id', 'model_kind'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('mine_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', name='notificationchannel', native_enum=False, length=48), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=48), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_notifications_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('REPRESENTATIVE_STATUTORY_RETURN', 'COMPLIANCE_SUMMARY', name='reportkind', native_enum=False, length=48), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('official_format_verified', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_reports_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_reports_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_mine_id'), ['mine_id'], unique=False)

    op.create_table('capa_items',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('VIOLATION', 'RISK_ALERT', 'INCIDENT', 'SENSOR_ANOMALY', 'OBLIGATION_BREACH', name='capasourcetype', native_enum=False, length=48), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'EVIDENCE_SUBMITTED', 'VERIFIED', 'CLOSED', 'ESCALATED', name='capastatus', native_enum=False, length=48), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('closure_evidence_doc_id', sa.Uuid(), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_capa_items_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closure_evidence_doc_id'], ['documents.id'], name=op.f('fk_capa_items_closure_evidence_doc_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_capa_items_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['statutory_rules.id'], name=op.f('fk_capa_items_rule_id_statutory_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_capa_items_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_items'))
    )
    with op.batch_alter_table('capa_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capa_items_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_capa_items_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_capa_items_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capa_items_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capa_items_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_capa_items_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_capa_items_status'), ['status'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('confirmed_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('was_corrected', sa.Boolean(), nullable=False),
    sa.Column('ocr_engine', sa.Enum('TESSERACT', 'BHASHINI', 'DEMO_FALLBACK', 'NONE', name='ocrengine', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extracted_fields_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_fields'))
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_document_id'), ['document_id'], unique=False)

    op.create_table('field_evidence',
    sa.Column('client_uuid', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('INSPECTION', 'ATTENDANCE', 'INCIDENT', name='evidencekind', native_enum=False, length=48), nullable=False),
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_skew_seconds', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy_m', sa.Float(), nullable=True),
    sa.Column('location_method', sa.Enum('GPS_SURFACE', 'GPS_PIT_MOUTH', 'QR_CHECKPOINT', 'NFC_CHECKPOINT', 'NONE', name='locationmethod', native_enum=False, length=48), nullable=False),
    sa.Column('checkpoint_code', sa.String(length=64), nullable=True),
    sa.Column('mock_location_reported', sa.Boolean(), nullable=True),
    sa.Column('spoof_flags', sa.JSON(), nullable=True),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('photo_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING_SYNC', 'SYNCED', name='syncstatus', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_field_evidence_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_field_evidence_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_field_evidence_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_evidence')),
    sa.UniqueConstraint('client_uuid', name='uq_field_evidence_client_uuid')
    )
    with op.batch_alter_table('field_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_evidence_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_evidence_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_evidence_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_evidence_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_evidence_sync_status'), ['sync_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_evidence_user_id'), ['user_id'], unique=False)

    op.create_table('mine_obligations',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('last_satisfied_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRING_SOON', 'EXPIRED', 'PENDING_VERIFICATION', 'MISSING', name='obligationstatus', native_enum=False, length=48), nullable=False),
    sa.Column('satisfying_document_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_mine_obligations_mine_id_mines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['statutory_rules.id'], name=op.f('fk_mine_obligations_rule_id_statutory_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['satisfying_document_id'], ['documents.id'], name=op.f('fk_mine_obligations_satisfying_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mine_obligations')),
    sa.UniqueConstraint('mine_id', 'rule_id', name='uq_mine_obligations_mine_rule')
    )
    with op.batch_alter_table('mine_obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mine_obligations_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mine_obligations_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mine_obligations_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mine_obligations_status'), ['status'], unique=False)

    op.create_table('anomaly_explanations',
    sa.Column('mine_id', sa.Uuid(), nullable=False),
    sa.Column('model_kind', sa.Enum('ACCIDENT_RISK_SUPERVISED', 'SENSOR_ANOMALY_ISOLATION_FOREST', 'RULE_BASED_BASELINE', name='modelkind', native_enum=False, length=48), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contributing_signals', sa.JSON(), nullable=True),
    sa.Column('capa_id', sa.Uuid(), nullable=True),
    sa.Column('provenance', sa.Enum('REAL_PUBLIC_DATA', 'SIMULATED', 'DEMO', 'LIVE_EXTERNAL_API', 'DEMO_FALLBACK', 'USER_SUPPLIED', name='dataprovenance', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['capa_id'], ['capa_items.id'], name=op.f('fk_anomaly_explanations_capa_id_capa_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], name=op.f('fk_anomaly_explanations_mine_id_mines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly_explanations'))
    )
    with op.batch_alter_table('anomaly_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_explanations_capa_id'), ['capa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomaly_explanations_mine_id'), ['mine_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('worker_code', sa.String(length=64), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=True),
    sa.Column('shift', sa.String(length=32), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_attendance_records_contractor_id_contractors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['field_evidence.id'], name=op.f('fk_attendance_records_evidence_id_field_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_contractor_id'), ['contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_worker_code'), ['worker_code'], unique=False)

    op.create_table('capa_events',
    sa.Column('capa_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'EVIDENCE_SUBMITTED', 'VERIFIED', 'CLOSED', 'ESCALATED', name='capastatus', native_enum=False, length=48), nullable=True),
    sa.Column('to_status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'EVIDENCE_SUBMITTED', 'VERIFIED', 'CLOSED', 'ESCALATED', name='capastatus', native_enum=False, length=48), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('evidence_doc_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_capa_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['capa_id'], ['capa_items.id'], name=op.f('fk_capa_events_capa_id_capa_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_doc_id'], ['documents.id'], name=op.f('fk_capa_events_evidence_doc_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_events'))
    )
    with op.batch_alter_table('capa_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capa_events_capa_id'), ['capa_id'], unique=False)

    op.create_table('incident_reports',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=48), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('FORM', 'VOICE', name='incidentsource', native_enum=False, length=48), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('audio_hash', sa.String(length=64), nullable=True),
    sa.Column('source_language', sa.String(length=16), nullable=True),
    sa.Column('original_transcript', sa.Text(), nullable=True),
    sa.Column('translated_transcript', sa.Text(), nullable=True),
    sa.Column('asr_provider_status', sa.Enum('LIVE_BHASHINI', 'BHASHINI_UNAVAILABLE', 'DEMO_FALLBACK', name='providerstatus', native_enum=False, length=48), nullable=True),
    sa.Column('nmt_provider_status', sa.Enum('LIVE_BHASHINI', 'BHASHINI_UNAVAILABLE', 'DEMO_FALLBACK', name='providerstatus', native_enum=False, length=48), nullable=True),
    sa.Column('transcript_provenance', sa.Enum('REAL_PUBLIC_DATA', 'SIMULATED', 'DEMO', 'LIVE_EXTERNAL_API', 'DEMO_FALLBACK', 'USER_SUPPLIED', name='dataprovenance', native_enum=False, length=48), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['field_evidence.id'], name=op.f('fk_incident_reports_evidence_id_field_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_reports'))
    )
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_reports_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_reports_source'), ['source'], unique=False)

    op.create_table('inspection_findings',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('compliant', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=48), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['field_evidence.id'], name=op.f('fk_inspection_findings_evidence_id_field_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['statutory_rules.id'], name=op.f('fk_inspection_findings_rule_id_statutory_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_findings'))
    )
    with op.batch_alter_table('inspection_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_findings_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_findings_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_findings_rule_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_findings_evidence_id'))

    op.drop_table('inspection_findings')
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_reports_source'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_severity'))
        batch_op.drop_index(batch_op.f('ix_incident_reports_evidence_id'))

    op.drop_table('incident_reports')
    with op.batch_alter_table('capa_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capa_events_capa_id'))

    op.drop_table('capa_events')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_worker_code'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_contractor_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('anomaly_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_explanations_mine_id'))
        batch_op.drop_index(batch_op.f('ix_anomaly_explanations_capa_id'))

    op.drop_table('anomaly_explanations')
    with op.batch_alter_table('mine_obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mine_obligations_status'))
        batch_op.drop_index(batch_op.f('ix_mine_obligations_rule_id'))
        batch_op.drop_index(batch_op.f('ix_mine_obligations_next_due_date'))
        batch_op.drop_index(batch_op.f('ix_mine_obligations_mine_id'))

    op.drop_table('mine_obligations')
    with op.batch_alter_table('field_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_evidence_user_id'))
        batch_op.drop_index(batch_op.f('ix_field_evidence_sync_status'))
        batch_op.drop_index(batch_op.f('ix_field_evidence_mine_id'))
        batch_op.drop_index(batch_op.f('ix_field_evidence_kind'))
        batch_op.drop_index(batch_op.f('ix_field_evidence_device_id'))
        batch_op.drop_index(batch_op.f('ix_field_evidence_client_uuid'))

    op.drop_table('field_evidence')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_document_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('capa_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capa_items_status'))
        batch_op.drop_index(batch_op.f('ix_capa_items_source_type'))
        batch_op.drop_index(batch_op.f('ix_capa_items_severity'))
        batch_op.drop_index(batch_op.f('ix_capa_items_rule_id'))
        batch_op.drop_index(batch_op.f('ix_capa_items_mine_id'))
        batch_op.drop_index(batch_op.f('ix_capa_items_due_date'))
        batch_op.drop_index(batch_op.f('ix_capa_items_assigned_to'))

    op.drop_table('capa_items')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_mine_id'))
        batch_op.drop_index(batch_op.f('ix_reports_kind'))

    op.drop_table('reports')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_mine_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_ml_predictions_mine_kind')
        batch_op.drop_index(batch_op.f('ix_ml_predictions_mine_id'))

    op.drop_table('ml_predictions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_verification_status'))
        batch_op.drop_index(batch_op.f('ix_documents_rule_id'))
        batch_op.drop_index(batch_op.f('ix_documents_mine_id'))
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))
        batch_op.drop_index(batch_op.f('ix_documents_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_documents_contractor_id'))

    op.drop_table('documents')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_fingerprint'))

    op.drop_table('devices')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_row_hash'))
        batch_op.drop_index('ix_audit_log_entity')
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_subsidiary_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_mine_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('ml_features', schema=None) as batch_op:
        batch_op.drop_index('ix_ml_features_window')
        batch_op.drop_index(batch_op.f('ix_ml_features_mine_id'))

    op.drop_table('ml_features')
    with op.batch_alter_table('environmental_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environmental_readings_sensor_kind'))
        batch_op.drop_index(batch_op.f('ix_environmental_readings_provenance'))
        batch_op.drop_index(batch_op.f('ix_environmental_readings_mine_id'))
        batch_op.drop_index('ix_env_readings_mine_time')

    op.drop_table('environmental_readings')
    with op.batch_alter_table('contractor_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractor_sites_mine_id'))
        batch_op.drop_index(batch_op.f('ix_contractor_sites_contractor_id'))
        batch_op.drop_index(batch_op.f('ix_contractor_sites_contract_end'))

    op.drop_table('contractor_sites')
    with op.batch_alter_table('mines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mines_subsidiary_id'))
        batch_op.drop_index(batch_op.f('ix_mines_status'))
        batch_op.drop_index(batch_op.f('ix_mines_mine_type'))
        batch_op.drop_index(batch_op.f('ix_mines_code'))

    op.drop_table('mines')
    with op.batch_alter_table('subsidiaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subsidiaries_code'))

    op.drop_table('subsidiaries')
    with op.batch_alter_table('statutory_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_rules_severity'))
        batch_op.drop_index(batch_op.f('ix_statutory_rules_rule_code'))

    op.drop_table('statutory_rules')
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_artifacts_model_kind'))

    op.drop_table('model_artifacts')
    with op.batch_alter_table('contractors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractors_status'))
        batch_op.drop_index(batch_op.f('ix_contractors_code'))

    op.drop_table('contractors')
    # ### end Alembic commands ###
